### ISSUE TITLE
不能获得“application id "com.eusoft.eudic"”

### ISSUE THREAD

**Issue by sltzwfy** [HanleyLee/alfred-eudic-workflow#1]
使用中发现的

**Comment by HanleyLee** [comment]
请问使用的是Mac App Store 版的 eudic 还是直接从官网下载的版本?

**Comment by sltzwfy** [comment]
app store上下载的

**Comment by HanleyLee** [comment]
嗯, 我当时考虑到这个问题了, 不过我个人使用的是官网版本, 所以对 MacApp Store 版本的没有进行适配, 我这两天对商店版本进行一下适配, 你那边如果有条件的话可以找出 MacApp Store 版本 eudic 的 application id, 在 Workflow 里面将 application id 手动更新, 或者等我更新.

**Comment by sltzwfy** [comment]
换成官网版本确实可以了，但是好像这个速度有点慢，打开软件后要一两秒才能搜索。

**Comment by vda96** [comment]
@HanleyLee 请问下如何获取application id还有workflow里改哪些地方？

**Comment by HanleyLee** [comment]
> @HanleyLee 请问下如何获取application id还有workflow里改哪些地方？

1. 可以在终端中使用 `osascript -e 'id of app "Finder"'` 获得 `application id`(把 `Finder` 替换成你指定的 app 名字)
2. 你可以找一个入门的 workflow 教程看看, 很简单的

**Comment by lixw1021** [comment]
nice workflow 
我的版本Id 是 “com.eusoft.freeeudic” 改完就好
