### ISSUE TITLE
好像不能发音。

### ISSUE THREAD

**Issue by heguohui2018** [HanleyLee/alfred-eudic-workflow#2]

**Comment by HanleyLee** [comment]
你是在 Alfred 搜索框激活情况下输入按下 `⌘ ⏎` 了吗

**Comment by heguohui2018** [comment]
是的

**Comment by HanleyLee** [comment]
插件的其他功能正常吗? 比如选中情况下的搜索?

**Comment by heguohui2018** [comment]
我又试了一下，双击 option键没有弹出搜索窗口，我换成其他快捷键就可以弹出，使用了几次都不能达到你在redame里所达到的效果。

zh这是我的系统，我使用的alfred版本是 4.1
<img width="304" alt="截屏2020-10-12 18 12 51" src="https://user-images.githubusercontent.com/35359288/95735177-12ddb400-0cb7-11eb-8237-6e389f8953c1.png">

**Comment by HanleyLee** [comment]
如果你确实在 `Alfred` 中设置了双击 `⌥` 弹出搜索窗口但是没有反应的话你应该检查下 `Alfred` 或者其他软件是否对 `⌥` 有占用, 发音功能是在搜索框中有输入值时然后按下 `⌘ ⏎` 才会触发
