### ISSUE TITLE
【需求】强化 workflow

### ISSUE THREAD

**Issue by 0xe69e97** [hanleylee/alfred-eudic-workflow#5]
1. 有想法支持生词本的功能吗？
2. 可以弄成类似有道词典那种翻译吗？输入内容后，自动将翻译的信息展示

![image](https://cdn.jsdelivr.net/gh/0xe69e97/image-PicX@master/Blog/image.791m8fslokg0.png)

**Comment by 0xe69e97** [comment]
嘿嘿，就是问问大佬有没有这两个需求的想法哈～

**Comment by hanleylee** [comment]
实话说, 我也很想, 但是基本没有可能在 Eudic 上做出这种效果, 现在的功能完全是根据欧路官方暴露出来的 AppleScript 接口做的, 官方暴露的接口及其有限, 所以 Eudic 基本不可能做出像你图片的这种效果的.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/35610874/144588017-c5230047-7fb7-4d0a-aaea-508ea0fbdc31.png">


如果你有相应的思路可以分享一下, 我对这个需求同样非常有兴趣
